name: milestones

on:
    pull_request:
        types: [ closed ]

jobs:
    set_milestone:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Set milestone
              if: github.event.pull_request.merged && github.event.pull_request.milestone == null
              # token should have `repo` scope
              run: python scripts/set_milestone.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }} --pull-request ${{ github.event.pull_request.number }}
